language: java

dist: xenial
addons:
  apt:
    packages:
    - libgconf-2-4
jdk:
  - openjdk8
  - openjdk11

services:
  - docker

env:
  - img=existdb/existdb:latest
  # No need to check for backwards compatibility
  # - img=existdb/existdb:release

cache:
  directories:
  - $HOME/.m2

before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - mvn clean package -DskipTests -q

before_script:
  - docker cp ./target/*.xar exist-ci:exist/autodeploy/111.xar
  - docker start exist-ci
  # exist needs time
  - sleep 30

script:
  - mvn validate
  - mvn test
  - npm run cypress -- --record

after_success:
  - docker ps

notifications:
  slack: exist-db:IXzUdqA0n11cnxaDz43ZQgdX
